#!/usr/bin/env node

const fs = require('fs')
const { promisify } = require('util')
const read = promisify(fs.readFile)
const write = promisify(fs.writeFile)
const { hexToArrayBuffer, sortArrayBuffers } = require('./utils')

main()

async function main() {
  const [
    ,
    ,
    inputFilename,
    outputFilename = `${inputFilename}.bin`,
  ] = process.argv
  const writeStream = fs.createWriteStream(outputFilename)
  console.log(`${inputFilename} -> ${outputFilename}`)
  console.log(`reading...`)
  const data = await read(inputFilename)
  console.log('encoding...')
  const addresses = data
    .toString()
    .trim()
    .split('\n')
    .map(hexToArrayBuffer)
    .sort(sortArrayBuffers)
  const { length } = addresses
  console.log(`writing...`)
  for (let i = 0; i < length; i++) {
    writeStream.write(new Buffer(addresses[i]))
  }
  console.log('done! ✨')
}
